export const settingsCopy = {
  es: {
    eyebrow: "A TU MANERA", title: "Tu estudio, tu espacio", description: "Los detalles que hacen este espacio tuyo.",
    profile: "Identidad del estudio", profileNote: "Así aparecerás en tu espacio de trabajo.", name: "Tu nombre de artista", studio: "Nombre del estudio", optional: "opcional", studioPlaceholder: "El nombre de tu estudio", email: "Correo de acceso", save: "Guardar cambios", saving: "Guardando…", saved: "Cambios guardados. Tu espacio ya está actualizado.",
    profileErrors: { name: "Escribe un nombre válido de hasta 80 caracteres.", studio: "El nombre del estudio debe tener hasta 80 caracteres y estar en una sola línea.", save: "No se han guardado los cambios. Inténtalo de nuevo." },
    preferences: "Idioma y región", preferencesNote: "Trabaja en el idioma que prefieras.", region: "España · EUR (€)", timezone: "Las citas se muestran en la hora peninsular de España (Europe/Madrid), incluidos los cambios de horario de verano.", language: "Idioma",
    security: "Seguridad", securityNote: "Al cambiar la contraseña se cerrarán tus otras sesiones.", currentPassword: "Contraseña actual", newPassword: "Nueva contraseña", confirmPassword: "Repite la nueva contraseña", passwordHint: "Entre 8 y 128 caracteres. Usa una contraseña única.", changePassword: "Cambiar contraseña", passwordSaved: "Contraseña cambiada. Las otras sesiones se han cerrado.",
    passwordErrors: { current: "Comprueba tu contraseña actual.", length: "La nueva contraseña debe tener entre 8 y 128 caracteres.", match: "Las nuevas contraseñas no coinciden.", same: "Elige una contraseña diferente a la actual.", save: "No se ha cambiado la contraseña. Inténtalo de nuevo." },
    createPassword: "Crear contraseña", createPasswordNote: "Añade una contraseña para entrar también con tu correo. Tu cuenta y todos tus datos seguirán siendo los mismos.", google: "Acceso con Google", googleNote: "Conecta la cuenta de Google con el mismo correo para acceder a este mismo espacio de artista.", googleConnected: "Google está conectado a tu cuenta de artista.", googleError: "No se pudo conectar Google. Usa la cuenta con el mismo correo de tu artista e inténtalo de nuevo.",
    data: "Tus datos", dataNote: "Descarga tus clientes, citas, pagos registrados y los datos de tus diseños en un archivo JSON. Las imágenes se descargan desde cada diseño y no se incluyen en este archivo.", export: "Descargar mis datos", privateNote: "El archivo contiene datos de tus clientes. Guárdalo en un lugar privado.",
  },
  en: {
    eyebrow: "MAKE IT YOURS", title: "Your studio, your space", description: "The details that make this workspace your own.",
    profile: "Studio identity", profileNote: "How you appear in your workspace.", name: "Your artist name", studio: "Studio name", optional: "optional", studioPlaceholder: "Your studio's name", email: "Sign-in email", save: "Save changes", saving: "Saving…", saved: "Changes saved. Your workspace is up to date.",
    profileErrors: { name: "Enter a valid name of up to 80 characters.", studio: "Use a studio name of up to 80 characters on a single line.", save: "Changes could not be saved. Please try again." },
    preferences: "Language & region", preferencesNote: "Work in the language you prefer.", region: "Spain · EUR (€)", timezone: "Appointments use mainland Spain time (Europe/Madrid), including daylight saving changes.", language: "Language",
    security: "Security", securityNote: "Changing your password signs out your other sessions.", currentPassword: "Current password", newPassword: "New password", confirmPassword: "Repeat new password", passwordHint: "Between 8 and 128 characters. Use a unique password.", changePassword: "Change password", passwordSaved: "Password changed. Your other sessions have been signed out.",
    passwordErrors: { current: "Check your current password.", length: "Use a new password between 8 and 128 characters.", match: "The new passwords do not match.", same: "Choose a password different from your current one.", save: "Password could not be changed. Please try again." },
    createPassword: "Create password", createPasswordNote: "Add a password to also sign in with your email. Your account and all your data stay the same.", google: "Google access", googleNote: "Connect the Google account with the same email to sign in to this same artist workspace.", googleConnected: "Google is connected to your artist account.", googleError: "Google could not be connected. Use the account with your artist's email and try again.",
    data: "Your data", dataNote: "Download your clients, appointments, recorded payments, and design details as a JSON file. Download images from each design; they are not included in this file.", export: "Download my data", privateNote: "This file contains your clients' details. Keep it somewhere private.",
  },
};
export type SettingsCopy = typeof settingsCopy.es | typeof settingsCopy.en;
